# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Build Documentation

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: "${{ secrets.NIPREPS_BOT }}"
    - name: Fetch all tags (for setuptools_scm to work)
      if: github.ref == 'refs/heads/master'
      run: |
        /usr/bin/git -c protocol.version=2 fetch --tags --prune --unshallow origin
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build in confined environment and interpolate version
      run: |
        python -m pip install -U pip "setuptools >= 42.0" "setuptools_scm[toml] >= 3.4"
        python setup.py --version
        python -m pip install -r docs/requirements.txt
        make -C docs/ html
